### ISSUE TITLE
accuracy + production problems

### ISSUE THREAD

**Issue by SaddamBInSyed** [feat7/thermal-screening#1]
Hi @feat7 

Thanks for your work,

I would like to ask How I can measure the accuracy of the code and what are the things I need to consider if I want to use this code into real-time my project ( video feed from thermal camera not from sample video)

please advise,

**Comment by feat7** [comment]
You have to first of all the specifications of the thermal camera that you're using.
You'll get a scale on how to convert the pixel intensities to temperature.
Moreover, you also need to find some data in real world.
Eg. Wherever the camera is setup, you'll need to adjust the scale accordingly because some external factors do matter.

Initially for testing, you need to know the real temperature of a person (good if you do with multiple people) - do it with thermometer.
See from the feed and algorithms, how much temperature you need to adjust, how much is the mean and standard deviation?

Calibrate the scale accordingly.

**Comment by feat7** [comment]
Moreover, do the things I have mentioned in the blog. Eg. Use some face detection in combination of this.
The accuracy totally depends upon thermal camera, surroundings and how you setup the threshold.
For binary threshold, you can setup different threshold. Default is 200.
For temperature you can setup on how much temperature should be safe.

**Comment by SaddamBInSyed** [comment]
Thank you for the response.

I'm waiting for my thermal camera to arrive.

I will update the results once I tested.

Cheers.

**Comment by SaddamBInSyed** [comment]
hi @feat7 
I heard that all the available thermal camera comes with temperature detection sdk and we can see the same into the CCTV frames (temperature embedded) 

so in that case, there is no use for separate temperature detection application like this repo?

please advise.

**Comment by feat7** [comment]
It depends. If the camera company is providing you SDK it's good. But you might want to tweak the algorithms in your way then this is helpful. It's easier to calibrate when you write the code instead of someone else has written it for you.
Some good thermal camera companies provide the sdk which you can use but that's not the end of the world.
